"use strict";

module.exports = {
  ASSET_EVENT_TABLE: "AssetEvents",
  ASSET_TABLE: "Assets",
  CUSTODIAN_TABLE: "Custodians",
  DAYBOOK_ADDITIONAL_CHARGE_TABLE: "DayBookAdditionalCharges",
  DAYBOOK_ENTRY_SEQUENCE_TABLE: "DayBookEntrySequences",
  DAYBOOK_ITEM_SERIAL_TABLE: "DayBookItemSerials",
  DAYBOOK_ITEM_TABLE: "DayBookItems",
  DAYBOOK_TABLE: "DayBooks",
  EMPLOYEE_TABLE: "Employees",
  FORENSIC_AUDIT_ARCHIVE_TABLE: "ForensicAuditArchives",
  FORENSIC_AUDIT_LOG_TABLE: "ForensicAuditLogs",
  GATE_PASS_ITEM_TABLE: "GatePassItems",
  GATE_PASS_TABLE: "GatePasses",
  ISSUED_ITEM_TABLE: "IssuedItems",
  ITEM_CATEGORY_GROUP_TABLE: "ItemCategoryGroups",
  ITEM_CATEGORY_HEAD_TABLE: "ItemCategoryHeads",
  ITEM_CATEGORY_TABLE: "ItemCategories",
  ITEM_MASTER_ALIAS_TABLE: "ItemMasterAliases",
  ITEM_MASTER_TABLE: "ItemMasters",
  MATERIAL_ISSUE_RECEIPT_TABLE: "MaterialIssueReceipts",
  REQUISITION_ACTION_TABLE: "RequisitionActions",
  REQUISITION_ATTACHMENT_TABLE: "RequisitionAttachments",
  REQUISITION_ITEM_TABLE: "RequisitionItems",
  REQUISITION_TABLE: "Requisitions",
  STOCK_MOVEMENT_TABLE: "StockMovements",
  STOCK_TABLE: "Stocks",
  VENDOR_TABLE: "Vendors",
};
